# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Turku Data Science Group
email: leo.lahti@iki.fi
description: Research homepage. University of Turku, Finland. PI Leo Lahti. 
  > # You can edit this line in _config.yml. It will appear in your document head meta (for  Google search results) and in your feed.xml site description.
baseurl: ""
url: ""

include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false



# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links



# From http://tuxette.nathalievilla.org/?p=1426#more-1426
# Styles https://github.com/citation-style-language/styles
scholar:  
  style: _layouts/mycitationstyle.csl
  locale: en

  sort_by: year
  order: descending

  source: publications
  bibliography: lahti.bib
  bibliography_template: bibliography # from _layouts folder / or "{ reference }"

  replace_strings: true
  join_strings: true  

  details_dir:    bib
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"
